=== SharpenYourSword/recap-server/uploads/docket.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT gov_uscourts_docket (nonce, case_details, party_list?, document_list)>

<!ELEMENT nonce (#PCDATA)>

<!ELEMENT case_details (court, docket_num?, case_name?, pacer_case_num, date_case_filed?, date_case_terminated?, date_last_filing?, assigned_to?, referred_to?, case_cause?, nature_of_suit?, jury_demand?, jurisdiction?, demand?)>
<!ELEMENT court (#PCDATA)>
<!ELEMENT docket_num (#PCDATA)>
<!ELEMENT pacer_case_num (#PCDATA)>
<!ELEMENT case_name (#PCDATA)>
<!ELEMENT date_case_filed (#PCDATA)>
<!ELEMENT date_case_terminated (#PCDATA)>
<!ELEMENT date_last_filing (#PCDATA)>
<!ELEMENT assigned_to (#PCDATA)>
<!ELEMENT referred_to (#PCDATA)>
<!ELEMENT case_cause (#PCDATA)>
<!ELEMENT nature_of_suit (#PCDATA)>
<!ELEMENT jury_demand (#PCDATA)>
<!ELEMENT jurisdiction (#PCDATA)>
<!ELEMENT demand (#PCDATA)>

<!ELEMENT party_list (party*)>
<!ELEMENT party (name?, type?, extra_info?, attorney_list?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT extra_info (#PCDATA)>
<!ELEMENT attorney_list (attorney*)>
<!ELEMENT attorney (attorney_name, contact?, attorney_role?)>
<!ELEMENT attorney_name (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT attorney_role (#PCDATA)>

<!ELEMENT document_list (document*)>
<!ELEMENT document (pacer_doc_id?, pacer_de_seq_num?, pacer_dm_id?, date_filed?, date_entered?, long_desc?, short_desc?, upload_date?, available?, sha1?)>
<!ATTLIST document
    doc_num NMTOKEN #REQUIRED
    attachment_num NMTOKEN #REQUIRED>
<!ELEMENT pacer_doc_id (#PCDATA)>
<!ELEMENT pacer_de_seq_num (#PCDATA)>
<!ELEMENT pacer_dm_id (#PCDATA)>
<!ELEMENT date_filed (#PCDATA)>
<!ELEMENT date_entered (#PCDATA)>
<!ELEMENT long_desc (#PCDATA)>
<!ELEMENT short_desc (#PCDATA)>
<!ELEMENT upload_date (#PCDATA)>
<!ELEMENT available (#PCDATA)>
<!ELEMENT sha1 (#PCDATA)>

=== SharpenYourSword/recap-server/test_support/testdockets/noPartiesXML/candSomeAttys.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gov_uscourts_docket SYSTEM "docket.dtd">
<gov_uscourts_docket>
  <nonce>L6S3BN</nonce>
  <case_details>
    <court>cand2</court>
    <docket_num>3:08-cv-00177</docket_num>
    <case_name>Brady et al v. Deloitte &amp; Touche LLP et al</case_name>
    <pacer_case_num>7830</pacer_case_num>
    <date_case_filed>2008-01-10</date_case_filed>
    <assigned_to>Hon. Susan Illston</assigned_to>
    <case_cause>28:1331 Fed. Question</case_cause>
    <nature_of_suit>790 Labor: Other</nature_of_suit>
    <jury_demand>Plaintiff</jury_demand>
    <jurisdiction>Federal Question</jurisdiction>
  </case_details>
  <party_list>
    <party>
      <name>James Brady</name>
      <type>Plaintiff</type>
      <attorney_list>
        <attorney>
          <attorney_name>Wayne Scott Kreger</attorney_name>
          <contact>Milstein Adelman &amp; Kreger LLP
2800 Donald Douglas Loop North
Santa Monica, CA 90405
310-396-9600
Fax: 310-396-9635
Email: wkreger@maklawyers.com</contact>
          <attorney_role>LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
      </attorney_list>
    </party>
    <party>
      <name>Sarah Cavanagh</name>
      <type>Plaintiff</type>
      <extra_info>individually and on behalf of all others similarly situated</extra_info>
      <attorney_list>
        <attorney>
          <attorney_name>Wayne Scott Kreger</attorney_name>
          <contact>(See above for address)</contact>
          <attorney_role>TERMINATED: 06/22/2009
LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>William Anthony Baird</attorney_name>
          <contact>(See above for address)</contact>
          <attorney_role>LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Steven Stone Elster</attorney_name>
          <contact>(See above for address)</contact>
          <attorney_role>ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
      </attorney_list>
    </party>
    <party>
      <name>Deloitte &amp; Touche LLP</name>
      <type>Defendant</type>
      <extra_info>a limited liability partnership</extra_info>
      <attorney_list>
        <attorney>
          <attorney_name>James Edgar Boddy , Jr.</attorney_name>
          <contact>Morrison &amp; Foerster LLP
425 Market Street
San Francisco, CA 94105-2482
415/268-7081
Fax: 415/268-7522
Email: jboddy@mofo.com</contact>
          <attorney_role>LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Kathryn M. Davis</attorney_name>
          <contact>Morrison &amp; Foersterr LLP
101 Ygnacio Valley Road, Suite 450
P.O. Box 8130
Walnut Creek, CA 94596-8130
(925) 295-3372
Fax: (925) 946-9912
Email: kathryndavis@mofo.com</contact>
          <attorney_role>LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Linda E. Shostak</attorney_name>
          <contact>Morrison &amp; Foerster LLP
425 Market Street
San Francisco, CA 94105
(415) 268-7202
Email: lshostak@mofo.com</contact>
          <attorney_role>LEAD ATTORNEY
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Andrew Marc Paley</attorney_name>
          <contact>Seyfarth Shaw LLP
2029 Century Park East
Suite 3500
Los Angeles, CA 90067
310-201-5224
Fax: 310-201-5219
Email: apaley@seyfarth.com</contact>
          <attorney_role>TERMINATED: 08/11/2008
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Sheryl Lyn Skibbe</attorney_name>
          <contact>Seyfarth Shaw LLP
2029 Century Park East
Suite 3500
Los Angeles, CA 90067-3021
310-277-7200
Fax: 310-201-5219
Email: sskibbe@seyfarth.com</contact>
          <attorney_role>TERMINATED: 08/11/2008
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
      </attorney_list>
    </party>
    <party>
      <name>Deloitte Tax LLP</name>
      <type>Defendant</type>
      <extra_info>TERMINATED: 08/14/2008</extra_info>
      <attorney_list>
        <attorney>
          <attorney_name>Andrew Marc Paley</attorney_name>
          <contact>(See above for address)</contact>
          <attorney_role>TERMINATED: 08/14/2008
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
        <attorney>
          <attorney_name>Sheryl Lyn Skibbe</attorney_name>
          <contact>(See above for address)</contact>
          <attorney_role>TERMINATED: 08/14/2008
ATTORNEY TO BE NOTICED</attorney_role>
        </attorney>
      </attorney_list>
    </party>
  </party_list>
  <document_list>
    <document doc_num="1" attachment_num="0">
      <pacer_de_seq_num>7</pacer_de_seq_num>
      <pacer_dm_id>4069590</pacer_dm_id>
      <date_filed>2008-01-10</date_filed>
      <long_desc>COMPLAINT (summons issued); against Deloitte &amp; Touche LLP, Deloitte Tax LLP ( Filing fee $ 350, receipt number 34611014451.). Filed byJames Brady, Travis Call, Sarah Cavanagh. (ys, COURT STAFF) (Filed on 1/10/2008) (ys, COURT STAFF). (Entered: 01/11/2008)</long_desc>
    </document>
    <document doc_num="2" attachment_num="0">
      <pacer_de_seq_num>9</pacer_de_seq_num>
      <pacer_dm_id>4045400</pacer_dm_id>
      <date_filed>2008-01-10</date_filed>
      <long_desc>ADR SCHEDULING ORDER: Case Management Conference set for 4/18/2008 02:00 PM. Case Management Statement due by 4/11/2008. (Attachments: # 1 standing orders and cmc order)(ys, COURT STAFF) (Filed on 1/10/2008) (Entered: 01/11/2008)</long_desc>
    </document>
    <document doc_num="3" attachment_num="0">
      <pacer_de_seq_num>15</pacer_de_seq_num>
      <pacer_dm_id>4121283</pacer_dm_id>
      <date_filed>2008-02-08</date_filed>
      <long_desc>First AMENDED COMPLAINT against all defendants. Filed byJames Brady, Travis Call, Sarah Cavanagh. (Kreger, Wayne) (Filed on 2/8/2008) Modified on 2/11/2008 (ys, COURT STAFF). (Entered: 02/08/2008)</long_desc>
    </document>
  </document_list>
</gov_uscourts_docket>

=== SharpenYourSword/recap-server/test_support/testdockets/noPartiesXML/cit7830.xml
<!DOCTYPE gov_uscourts_docket SYSTEM "docket.dtd"> 
<gov_uscourts_docket> 
  <nonce>HMSYhO</nonce> 
  <case_details> 
    <court>cit</court> 
    <docket_num>1:09-cv-00523</docket_num> 
    <case_name>Franco Manufacturing Co., Inc. v. United States</case_name> 
    <pacer_case_num>7830</pacer_case_num> 
    <date_case_filed>2009-12-10</date_case_filed> 
    <date_last_filing>2009-12-10</date_last_filing> 
    <assigned_to>Unassigned</assigned_to> 
    <jury_demand>No</jury_demand> 
  </case_details> 
  <document_list> 
    <document doc_num="1" attachment_num="0"> 
      <pacer_de_seq_num>6</pacer_de_seq_num> 
      <pacer_dm_id>441201</pacer_dm_id> 
      <date_filed>2009-12-10</date_filed> 
      <date_entered>2009-12-10</date_entered> 
      <short_desc>Summons</short_desc> 
    </document> 
    <document doc_num="2" attachment_num="0"> 
      <pacer_de_seq_num>9</pacer_de_seq_num> 
      <pacer_dm_id>441204</pacer_dm_id> 
      <date_filed>2009-12-10</date_filed> 
      <date_entered>2009-12-10</date_entered> 
      <short_desc>Form 05 Information Statement</short_desc> 
    </document> 
    <document doc_num="3" attachment_num="0"> 
      <pacer_de_seq_num>11</pacer_de_seq_num> 
      <pacer_dm_id>441207</pacer_dm_id> 
      <date_filed>2009-12-10</date_filed> 
      <date_entered>2009-12-10</date_entered> 
      <short_desc>Form 13 Corporate Disclosure Statement</short_desc> 
    </document> 
    <document doc_num="4" attachment_num="0"> 
      <pacer_de_seq_num>13</pacer_de_seq_num> 
      <pacer_dm_id>441210</pacer_dm_id> 
      <date_filed>2009-12-10</date_filed> 
      <date_entered>2009-12-10</date_entered> 
      <long_desc>Summons served by Clerk's Office upon: Plaintiff, Defendant and Bureau of Customs and Border Protection. (Goell, Geoffrey) (Entered: 12/10/2009)</long_desc> 
      <short_desc>Service of 1581(a) Summons</short_desc> 
    </document> 
  </document_list> 
</gov_uscourts_docket>

=== SharpenYourSword/recap-server/test_support/testdockets/noPartiesXML/caedSomeParties.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gov_uscourts_docket SYSTEM "docket.dtd">
<gov_uscourts_docket>
  <nonce>KBWIzM</nonce>
  <case_details>
    <court>caed</court>
    <docket_num>1:09-cv-00515</docket_num>
    <case_name>(PC) Mitchell v. Rennick et al</case_name>
    <pacer_case_num>7830</pacer_case_num>
    <date_case_filed>2009-03-20</date_case_filed>
    <assigned_to>Magistrate Judge Sandra M. Snyder</assigned_to>
    <case_cause>42:1983 Prisoner Civil Rights</case_cause>
    <nature_of_suit>550 Prisoner: Civil Rights</nature_of_suit>
    <jury_demand>None</jury_demand>
    <jurisdiction>Federal Question</jurisdiction>
  </case_details>
  <party_list>
    <party>
      <name>Corey Mitchell</name>
      <type>Plaintiff</type>
      <attorney_list>
        <attorney>
          <attorney_name>Corey Mitchell</attorney_name>
          <contact>F-23331
SALINAS VALLEY STATE PRISON (1050)
PO BOX 1050
SOLEDAD, CA 93960-1050
PRO SE</contact>
        </attorney>
      </attorney_list>
    </party>
    <party>
      <name>Rennick</name>
      <type>Defendant</type>
      <extra_info>Correctional Officer</extra_info>
    </party>
    <party>
      <name>Bott</name>
      <type>Defendant</type>
      <extra_info>Correctional Officer</extra_info>
    </party>
    <party>
      <name>- Palmer</name>
      <type>Defendant</type>
      <extra_info>Correctional Officer</extra_info>
    </party>
  </party_list>
  <document_list>
    <document doc_num="1" attachment_num="0">
      <pacer_doc_id>03303140067</pacer_doc_id>
      <date_filed>2009-03-19</date_filed>
      <long_desc>PRISONER CIVIL RIGHTS COMPLAINT against Rennick, Bott, Palmer, W Williams, Demery by Corey Mitchell.(Figueroa, O) (Entered: 03/20/2009)</long_desc>
    </document>
  </document_list>
</gov_uscourts_docket>
